[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "t"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
serde_json = "1.0"
arboard = "3.4"
notify = "6.1"
tempfile = "3.8"
tokio = { version = "1.0", features = ["full"] }
